import React from 'react';
import {Audio, Sequence, staticFile} from 'remotion';
import {AUDIO, SCENES, SFX, TOTAL_FRAMES} from '../config';

/** Sound effects (public/sfx/*.wav, generated by scripts/make_sfx.py), voiceover and optional music bed. */
export const SfxTrack: React.FC = () => {
  // Pull effects back when a voice is present so they never compete with it.
  const sfxGain = AUDIO.sfxVolume * (AUDIO.voiceover ? 0.6 : 1);
  return (
    <>
      {SFX.map((c, i) => (
        <Sequence key={i} from={SCENES[c.scene].from + c.f} durationInFrames={90} name={`sfx:${c.sfx}`}>
          <Audio src={staticFile(`sfx/${c.sfx}.wav`)} volume={(c.vol ?? 0.5) * sfxGain} />
        </Sequence>
      ))}
      {AUDIO.voiceover && <Audio src={staticFile(AUDIO.voiceover)} volume={AUDIO.voiceVolume} />}
      {AUDIO.music && (
        <Audio
          src={staticFile(AUDIO.music)}
          volume={(f) => AUDIO.musicVolume * Math.min(1, f / 20, (TOTAL_FRAMES - f) / 45)}
        />
      )}
    </>
  );
};
