/** Audio routing. Picture timing lives in src/timeline.json. */
export const AUDIO = {
  // Drop a recorded Hindi voiceover (timed to VOICEOVER.md) into public/audio/ and set e.g. 'audio/voiceover.wav'.
  voiceover: null as string | null,
  voiceVolume: 1,
  // Synthesised score + sound design, generated by scripts/make_score.py.
  score: 'audio/score.wav',
  scoreVolume: 1,
  // How far the score drops when a voiceover is present.
  duckUnderVoice: 0.6,
};

/** Currency glyph on the ad-spend token and the falling lost-revenue particles. */
export const CURRENCY = '$';

/** Logo file in public/ (square, black background — it is screen-blended so the black drops out). */
export const LOGO = 'brand/logo.png';
